---
version: '3.7'
services:
        backend:
                build:
                        context: .
                        dockerfile: ./Dockerfile
                container_name: news_miner
                restart: unless-stopped
                volumes:
                        - ./webServer/logs:/home/taste/logs
                deploy:
                        resources:
                              limits:
                                  cpus: '0.25'
                                  memory: 700M
                              reservations:
                                  cpus: '0.15'
                                  memory: 300M
                expose:
                        - 5500
                env_file:
                        - .env
                networks:
                        - proxy

        scraper:
                build:
                        context: ./scraper
                        dockerfile: ./Dockerfile
                container_name: scraper
                deploy:
                        resources:
                              limits:
                                  cpus: '0.25'
                                  memory: 700M
                              reservations:
                                  cpus: '0.15'
                                  memory: 300M
                volumes:
                        - ./scraper/logs:/home/taste/logs
                expose:
                        - 5500
                env_file:
                        - .env
                networks:
                        - proxy

        db:
                image: postgres:15-alpine3.17
                ports:
                        - 6432:5432
                restart: always
                container_name: news_db
                environment:
                        - TZ=Asia/Seoul
                env_file:
                        - .postgres.env
                volumes:
                        - ./newsData:/var/lib/postgresql/data
networks:
        proxy:
                external: true
